# Site
name: 'My Big Property'
description: 'My Big Property is a free Jekyll theme for awesome people like you, Pinterest like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/my-big-property'
avatar: 'assets/images/logo.jpg'
disqus: ''
email: 'vc.wong.my@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
